name: Lint-project-1

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pre-commit hook
        run: |
          cd project1
          python -m pip install pre-commit
          pre-commit install
      - name: Linting
        run: |
          cd project1
          pre-commit run --files src/*
          pre-commit run --files test/*
          pre-commit run --files include/*
